/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t volatile *pClockRegister = (uint32_t*) 0x40023830;
	// Address to GPIOD mode register
	uint32_t volatile *pGPIODModeRegister = (uint32_t*) 0x40020C00;
	// Address to GPIOD output data register
	uint32_t volatile *pGPIODOutDataRegister = (uint32_t*) 0x40020C14;

	// Address to GPIOA mode register
	uint32_t volatile *pGPIOAModeRegister = (uint32_t*) 0x40020000;
	// Address to GPIOA input register
	uint32_t volatile *pGPIOAInpDataRegister = (uint32_t*) 0x40020010;

	// Activate the clock for GPIOD & GPIOA Peripheral in AHB1ENR
	*pClockRegister |= (1 << 3);
	*pClockRegister |= (1 << 0);

	// Configuring PD12 as Output (GPIOD mode register)
	*pGPIODModeRegister &= ~(3 << 24);
	*pGPIODModeRegister |= (1 << 24);

	// Configuring PA0 as Input (GPIOA mode register)
	*pGPIOAModeRegister &= ~(3 << 0);

	while(1){
		// Reading the 1st bit of the input data register. *pGPIOAInpDataRegister outputs 32 bits.
		// Therefore, we perform bitwise AND to zero out all the other bits and output just the 1st bit
		uint8_t pinStatus = (uint8_t) (*pGPIOAInpDataRegister & 0x1);
		if (pinStatus) {
			// Turn on the LED
			// Setting 12th bit of the output data register to make the output of PD12 HIGH
			*pGPIODOutDataRegister |= (1 << 12);
		} else {
			// Turn off the LED
			*pGPIODOutDataRegister &= ~(1 << 12);
		}

	}

}
