/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Address to RCC clock control register (AHB1ENR): RCC Base + Address Offset for Clock Control
	uint32_t *pClockRegister = (uint32_t*) 0x40023830;
	// Address to GPIOD mode register
	uint32_t *pGPIODModeRegister = (uint32_t*) 0x40020C00;
	// Address to GPIOD output data register
	uint32_t *pGPIODOutDataRegister = (uint32_t*) 0x40020C14;

	// 1. Activate the clock for GPIOD peripheral (AHB1ENR register)
	/* uint32_t temp = *pClockRegister; // read
	temp |= 0x08; // modify
	*pClockRegister = temp; // write */
	*pClockRegister |= (1 << 3);

	// 2. Configuring the mode of the PD12 pin as Output --> 01 (clear 24th and 25th bit, then write)
	/*
	*pGPIODModeRegister &= ~(1 << 24); // clear
	*pGPIODModeRegister &= ~(1 << 25); // clear
	*/
	// Instead of using 2 lines, we can combine in one:
	*pGPIODModeRegister &= ~(3 << 24);
	*pGPIODModeRegister |= (1 << 24); // set

	// 3. Setting 12th bit of the output data register to make the output of PD12 HIGH
	*pGPIODOutDataRegister |= (1 << 12);

	// INTRODUCING SMALL DELAY

    /* Loop forever */
	for(;;);
}
